import type {
  ChatMessage,
  Comment,
  DestinyStory,
  ElysiumUser,
  LearnPath,
  MessageThread,
  NexusHub,
  Post,
  VoiceRoom,
} from "./types";

const now = Date.now();

export const SEED_USERS: ElysiumUser[] = [
  {
    id: "u-self",
    name: "You",
    handle: "@you",
    avatarColor: "#B57BFF",
    avatarGlyph: "Y",
    bio: "Designing futures. Always tuning in.",
    introVoiceSeconds: 12,
    city: "Lisbon",
    tags: ["builder", "synth-curious", "night-walker"],
    destinations: ["Lisbon", "AR-2030", "Founders"],
    alignmentScore: 0.82,
    weeklyVisitors: 47,
    online: true,
  },
  {
    id: "u-aria",
    name: "Aria Volkov",
    handle: "@aria.signal",
    avatarColor: "#5EEAD4",
    avatarGlyph: "A",
    bio: "Writing music for buildings.",
    introVoiceSeconds: 9,
    city: "Berlin",
    tags: ["composer", "introvert", "deep-listener"],
    destinations: ["Berlin", "Sound", "Healing"],
    alignmentScore: 0.78,
    weeklyVisitors: 312,
    online: true,
  },
  {
    id: "u-kenji",
    name: "Kenji Park",
    handle: "@kenji.craft",
    avatarColor: "#FFD56B",
    avatarGlyph: "K",
    bio: "Indie dev. Slow software, fast ideas.",
    introVoiceSeconds: 14,
    city: "Seoul",
    tags: ["dev", "minimalist", "collector"],
    destinations: ["Seoul", "OSS", "Game-dev"],
    alignmentScore: 0.91,
    weeklyVisitors: 188,
    online: true,
  },
  {
    id: "u-noor",
    name: "Noor Hadid",
    handle: "@noor.atlas",
    avatarColor: "#F472B6",
    avatarGlyph: "N",
    bio: "Mapping cities by their poems.",
    introVoiceSeconds: 7,
    city: "Beirut",
    tags: ["writer", "wanderer", "warm"],
    destinations: ["Beirut", "Travel", "Poetry"],
    alignmentScore: 0.74,
    weeklyVisitors: 226,
    online: false,
  },
  {
    id: "u-ines",
    name: "Inés Castro",
    handle: "@ines.glow",
    avatarColor: "#FB7185",
    avatarGlyph: "I",
    bio: "Founder. Building soft tech for hard moments.",
    introVoiceSeconds: 18,
    city: "Mexico City",
    tags: ["founder", "empath", "strategist"],
    destinations: ["CDMX", "StartupLife", "Mental-health"],
    alignmentScore: 0.86,
    weeklyVisitors: 401,
    online: true,
  },
  {
    id: "u-theo",
    name: "Theo Marsh",
    handle: "@theo.field",
    avatarColor: "#34D399",
    avatarGlyph: "T",
    bio: "Field recordings, slow conversations.",
    introVoiceSeconds: 11,
    city: "Edinburgh",
    tags: ["audio", "thoughtful", "late-bloomer"],
    destinations: ["Edinburgh", "Sound", "Nature"],
    alignmentScore: 0.69,
    weeklyVisitors: 92,
    online: false,
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: "p-1",
    authorId: "u-aria",
    kind: "voice",
    body: "Recorded this at 4am — the city was perfectly still. Tell me what it makes you feel.",
    mediaTone: "nebula1",
    voiceSeconds: 23,
    destinations: ["Sound", "Berlin"],
    resonance: { spark: 412, flame: 88, echo: 34, sync: 21, resonate: 67, link: 19 },
    energy: 0.86,
    createdAt: now - 1000 * 60 * 12,
  },
  {
    id: "p-2",
    authorId: "u-ines",
    kind: "project",
    body: "Spinning up a small group to design a 'quiet panic button' for founders. Voice room Friday. Who's in?",
    mediaTone: "none",
    destinations: ["StartupLife", "Mental-health"],
    project: {
      tasks: [
        { label: "Define the moment", done: true },
        { label: "Sketch 3 interactions", done: false },
        { label: "Test with 5 founders", done: false },
      ],
    },
    resonance: { spark: 268, flame: 41, echo: 52, sync: 119, resonate: 12, link: 33 },
    energy: 0.74,
    createdAt: now - 1000 * 60 * 38,
    nestedPostIds: ["p-3"],
  },
  {
    id: "p-3",
    authorId: "u-kenji",
    kind: "classic",
    body: "Plotted from another post — here's a tiny prototype I made last week that might fit. Resonate-only haptics.",
    mediaTone: "nebula3",
    destinations: ["Dev"],
    resonance: { spark: 92, flame: 14, echo: 9, sync: 31, resonate: 5, link: 12 },
    energy: 0.51,
    createdAt: now - 1000 * 60 * 36,
  },
  {
    id: "p-4",
    authorId: "u-noor",
    kind: "destiny",
    body: "Wandered the corniche tonight. The sea felt like a friend that's been waiting up for me.",
    mediaTone: "nebula2",
    destinations: ["Beirut", "Travel"],
    resonance: { spark: 1204, flame: 312, echo: 87, sync: 44, resonate: 188, link: 61 },
    energy: 0.93,
    createdAt: now - 1000 * 60 * 90,
  },
  {
    id: "p-5",
    authorId: "u-theo",
    kind: "poll",
    body: "Best time to think clearly?",
    mediaTone: "none",
    poll: {
      options: [
        { label: "Right after waking", votes: 142 },
        { label: "On a long walk", votes: 318 },
        { label: "3am, alone", votes: 224 },
        { label: "In the shower (obviously)", votes: 87 },
      ],
    },
    resonance: { spark: 88, flame: 7, echo: 4, sync: 41, resonate: 12, link: 3 },
    energy: 0.42,
    createdAt: now - 1000 * 60 * 60 * 3,
  },
  {
    id: "p-6",
    authorId: "u-aria",
    kind: "question",
    body: "What's a song that resets your nervous system in 30 seconds?",
    mediaTone: "none",
    destinations: ["Sound", "Healing"],
    resonance: { spark: 511, flame: 28, echo: 19, sync: 67, resonate: 132, link: 22 },
    energy: 0.81,
    createdAt: now - 1000 * 60 * 60 * 5,
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "c-1",
    postId: "p-1",
    authorId: "u-noor",
    parentId: null,
    body: "Felt like the moment before someone says the thing they've been afraid to say.",
    resonance: 88,
    createdAt: now - 1000 * 60 * 10,
  },
  {
    id: "c-2",
    postId: "p-1",
    authorId: "u-aria",
    parentId: "c-1",
    body: "Yes — that's exactly the chord progression hiding underneath.",
    voiceSeconds: 6,
    resonance: 22,
    createdAt: now - 1000 * 60 * 9,
  },
  {
    id: "c-3",
    postId: "p-1",
    authorId: "u-theo",
    parentId: "c-1",
    body: "I want to layer field recordings under this. May I echo into a project?",
    resonance: 14,
    createdAt: now - 1000 * 60 * 7,
  },
  {
    id: "c-4",
    postId: "p-1",
    authorId: "u-kenji",
    parentId: null,
    body: "Made my chest hum. That's the test.",
    laughThread: false,
    resonance: 41,
    createdAt: now - 1000 * 60 * 6,
  },
  {
    id: "c-5",
    postId: "p-1",
    authorId: "u-ines",
    parentId: null,
    body: "okay but the cat in the back at 0:14 is the real composer",
    laughThread: true,
    resonance: 309,
    createdAt: now - 1000 * 60 * 4,
  },
  {
    id: "c-6",
    postId: "p-1",
    authorId: "u-noor",
    parentId: "c-5",
    body: "the cat is union now, please pay it",
    laughThread: true,
    resonance: 88,
    createdAt: now - 1000 * 60 * 3,
  },
];

export const SEED_STORIES: DestinyStory[] = [
  { id: "s-1", authorId: "u-aria", caption: "4am, Berlin", destinations: ["Sound"], toneIndex: 0, resonance: 412 },
  { id: "s-2", authorId: "u-noor", caption: "Corniche walk", destinations: ["Beirut"], toneIndex: 1, resonance: 988 },
  { id: "s-3", authorId: "u-ines", caption: "Founder Friday", destinations: ["StartupLife"], toneIndex: 2, resonance: 244 },
  { id: "s-4", authorId: "u-kenji", caption: "Build log #18", destinations: ["Dev"], toneIndex: 0, resonance: 132 },
  { id: "s-5", authorId: "u-theo", caption: "Forest take", destinations: ["Nature"], toneIndex: 1, resonance: 78 },
  { id: "s-6", authorId: "u-aria", caption: "Letting it breathe", destinations: ["Healing"], toneIndex: 2, resonance: 301 },
];

export const SEED_HUBS: NexusHub[] = [
  {
    id: "h-1",
    name: "Slow Software",
    tagline: "Indie devs building tools that breathe.",
    members: 12480,
    pulse: 0.81,
    toneIndex: 0,
    online: ["u-kenji", "u-aria", "u-self", "u-ines"],
    postIds: ["p-2", "p-3"],
    projectMode: true,
  },
  {
    id: "h-2",
    name: "Night Composers",
    tagline: "Music made between 1am and 5am.",
    members: 4380,
    pulse: 0.62,
    toneIndex: 1,
    online: ["u-aria", "u-theo"],
    postIds: ["p-1", "p-6"],
    projectMode: false,
  },
  {
    id: "h-3",
    name: "Quiet Founders",
    tagline: "Building hard things, slowly, with care.",
    members: 9120,
    pulse: 0.74,
    toneIndex: 2,
    online: ["u-ines", "u-self", "u-noor"],
    postIds: ["p-2"],
    projectMode: true,
  },
  {
    id: "h-4",
    name: "Field Notes",
    tagline: "Sound, place, attention.",
    members: 2104,
    pulse: 0.48,
    toneIndex: 1,
    online: ["u-theo", "u-noor"],
    postIds: ["p-4"],
    projectMode: false,
  },
];

export const SEED_THREADS: MessageThread[] = [
  {
    id: "t-1",
    participantIds: ["u-self", "u-aria"],
    lastMessage: "I echoed your 4am piece into the project — listen?",
    unread: 2,
    voice: true,
    pinned: true,
  },
  {
    id: "t-2",
    participantIds: ["u-self", "u-ines"],
    lastMessage: "Friday voice room — want to co-host?",
    unread: 0,
    voice: false,
    pinned: true,
  },
  {
    id: "t-3",
    participantIds: ["u-self", "u-kenji"],
    lastMessage: "Sent the resonance-only haptics prototype.",
    unread: 1,
    voice: false,
    pinned: false,
  },
  {
    id: "t-4",
    participantIds: ["u-self", "u-noor"],
    lastMessage: "the cat is union now",
    unread: 0,
    voice: false,
    pinned: false,
  },
];

export const SEED_CHATS: Record<string, ChatMessage[]> = {
  "t-1": [
    { id: "m-1", threadId: "t-1", authorId: "u-aria", body: "Did the post land okay?", createdAt: now - 1000 * 60 * 60 },
    { id: "m-2", threadId: "t-1", authorId: "u-self", body: "It cracked something open. I want more.", createdAt: now - 1000 * 60 * 55 },
    { id: "m-3", threadId: "t-1", authorId: "u-aria", body: "Echoed into the project chat — voice note inside.", voiceSeconds: 9, createdAt: now - 1000 * 60 * 12 },
    { id: "m-4", threadId: "t-1", authorId: "u-aria", body: "I echoed your 4am piece into the project — listen?", createdAt: now - 1000 * 60 * 4 },
  ],
};

export const SEED_VOICE_ROOMS: VoiceRoom[] = [
  { id: "vr-1", topic: "What stops you from finishing?", vibe: "Tender", hostId: "u-ines", speakers: ["u-ines", "u-kenji"], listeners: 184, live: true },
  { id: "vr-2", topic: "Songs that reset your day", vibe: "Warm", hostId: "u-aria", speakers: ["u-aria", "u-theo", "u-noor"], listeners: 422, live: true },
  { id: "vr-3", topic: "Slow software — show & tell", vibe: "Curious", hostId: "u-kenji", speakers: ["u-kenji"], listeners: 91, live: true },
  { id: "vr-4", topic: "City walks, quietly described", vibe: "Quiet", hostId: "u-noor", speakers: ["u-noor"], listeners: 58, live: false },
];

export const SEED_PATHS: LearnPath[] = [
  { id: "lp-1", title: "Composing for Buildings", curator: "Aria Volkov", modules: 8, progress: 0.42, toneIndex: 0, category: "Sound" },
  { id: "lp-2", title: "Founder Nervous System", curator: "Inés Castro", modules: 12, progress: 0.18, toneIndex: 2, category: "Wellness" },
  { id: "lp-3", title: "Slow Software, fast ideas", curator: "Kenji Park", modules: 10, progress: 0.71, toneIndex: 1, category: "Craft" },
  { id: "lp-4", title: "Cities as Poems", curator: "Noor Hadid", modules: 6, progress: 0.0, toneIndex: 0, category: "Writing" },
  { id: "lp-5", title: "Field Recording 101", curator: "Theo Marsh", modules: 5, progress: 1, toneIndex: 1, category: "Sound" },
];
