/**
 * Elysium Seed Expansion — Expanded User Network for Cold Start
 *
 * Adds 42 additional seed users to the 8 existing ones, solving the
 * cold start problem identified in the 20K-user simulation.
 * These users represent diverse demographics, interests, and regions.
 *
 * This module is a NEW file — it does not alter any existing code.
 * The seed.ts file is NOT modified. Instead, this module exports
 * additional users that can be merged at the context level.
 *
 * Usage (in ResonanceContext or a new provider):
 *   import { EXPANDED_USERS } from "@/services/seed-expansion";
 *   const allUsers = [...SEED_USERS, ...EXPANDED_USERS];
 */

import type { ElysiumUser, Post, VoiceRoom } from "@/lib/types";

const now = Date.now();

export const EXPANDED_USERS: ElysiumUser[] = [
  // ── Gen Z Creators ─────────────────────────────────────────
  {
    id: "u-zara",
    name: "Zara Chen",
    handle: "@zara.pixel",
    avatarColor: "#F472B6",
    avatarGlyph: "Z",
    bio: "Digital art, 3D worlds, and late-night coding.",
    introVoiceSeconds: 8,
    city: "Shanghai",
    tags: ["creative", "dev", "night-walker"],
    destinations: ["Shanghai", "Dev", "Game-dev"],
    alignmentScore: 0.78,
    weeklyVisitors: 224,
    followers: 8421,
    following: 312,
    online: true,
  },
  {
    id: "u-marco",
    name: "Marco Silva",
    handle: "@marco.beats",
    avatarColor: "#5EEAD4",
    avatarGlyph: "M",
    bio: "Making beats between classes. Lo-fi everything.",
    introVoiceSeconds: 6,
    city: "São Paulo",
    tags: ["composer", "curious", "collector"],
    destinations: ["Sound", "Healing", "São Paulo"],
    alignmentScore: 0.72,
    weeklyVisitors: 156,
    followers: 4218,
    following: 488,
    online: true,
  },
  {
    id: "u-luna",
    name: "Luna Park",
    handle: "@luna.draw",
    avatarColor: "#A78BFA",
    avatarGlyph: "L",
    bio: "Illustrator. Drawing feelings since 2019.",
    introVoiceSeconds: 10,
    city: "Seoul",
    tags: ["creative", "introvert", "color-obsessed"],
    destinations: ["Seoul", "Film", "Dev"],
    alignmentScore: 0.82,
    weeklyVisitors: 312,
    followers: 12482,
    following: 211,
    online: false,
  },
  {
    id: "u-diego",
    name: "Diego Ramirez",
    handle: "@diego.flow",
    avatarColor: "#FFD56B",
    avatarGlyph: "D",
    bio: "Street photography and spoken word.",
    introVoiceSeconds: 9,
    city: "Mexico City",
    tags: ["filmmaker", "wanderer", "warm"],
    destinations: ["CDMX", "Film", "Travel"],
    alignmentScore: 0.74,
    weeklyVisitors: 188,
    followers: 5621,
    following: 902,
    online: true,
  },

  // ── Indie Developers ───────────────────────────────────────
  {
    id: "u-sam",
    name: "Sam Rivera",
    handle: "@sam.dev",
    avatarColor: "#34D399",
    avatarGlyph: "S",
    bio: "Building tools for people who think differently.",
    introVoiceSeconds: 14,
    city: "Portland",
    tags: ["dev", "minimalist", "builder"],
    destinations: ["Dev", "OSS", "Founders"],
    alignmentScore: 0.91,
    weeklyVisitors: 267,
    followers: 6124,
    following: 188,
    online: true,
  },
  {
    id: "u-lena",
    name: "Lena Schmidt",
    handle: "@lena.code",
    avatarColor: "#FB7185",
    avatarGlyph: "L",
    bio: "Backend by day, generative art by night.",
    introVoiceSeconds: 11,
    city: "Berlin",
    tags: ["dev", "creative", "night-walker"],
    destinations: ["Berlin", "Sound", "Dev"],
    alignmentScore: 0.85,
    weeklyVisitors: 192,
    followers: 3842,
    following: 244,
    online: false,
  },
  {
    id: "u-kai",
    name: "Kai Tanaka",
    handle: "@kai.design",
    avatarColor: "#B57BFF",
    avatarGlyph: "K",
    bio: "Design systems and the spaces between them.",
    introVoiceSeconds: 12,
    city: "Tokyo",
    tags: ["dev", "minimalist", "patient"],
    destinations: ["Tokyo", "Dev", "OSS"],
    alignmentScore: 0.88,
    weeklyVisitors: 341,
    followers: 9442,
    following: 521,
    online: true,
  },
  {
    id: "u-priya",
    name: "Priya Sharma",
    handle: "@priya.build",
    avatarColor: "#F97316",
    avatarGlyph: "P",
    bio: "Full-stack founder. Shipping slow, thinking fast.",
    introVoiceSeconds: 13,
    city: "Bangalore",
    tags: ["founder", "dev", "strategist"],
    destinations: ["Bangalore", "StartupLife", "Dev"],
    alignmentScore: 0.86,
    weeklyVisitors: 401,
    followers: 14204,
    following: 642,
    online: true,
  },

  // ── Musicians & Audio ──────────────────────────────────────
  {
    id: "u-amara",
    name: "Amara Obi",
    handle: "@amara.voice",
    avatarColor: "#F472B6",
    avatarGlyph: "A",
    bio: "Voice artist. The world needs more listening.",
    introVoiceSeconds: 18,
    city: "Lagos",
    tags: ["audio", "deep-listener", "warm"],
    destinations: ["Lagos", "Sound", "Healing"],
    alignmentScore: 0.79,
    weeklyVisitors: 288,
    followers: 7821,
    following: 344,
    online: true,
  },
  {
    id: "u-felix",
    name: "Felix Noir",
    handle: "@felix.noir",
    avatarColor: "#5EEAD4",
    avatarGlyph: "F",
    bio: "Jazz at 3am. The city is my instrument.",
    introVoiceSeconds: 15,
    city: "Paris",
    tags: ["composer", "night-walker", "synth-curious"],
    destinations: ["Paris", "Sound", "Healing"],
    alignmentScore: 0.76,
    weeklyVisitors: 412,
    followers: 11204,
    following: 521,
    online: false,
  },
  {
    id: "u-yuki",
    name: "Yuki Sato",
    handle: "@yuki.field",
    avatarColor: "#A78BFA",
    avatarGlyph: "Y",
    bio: "Field recordings from the Japanese countryside.",
    introVoiceSeconds: 11,
    city: "Kyoto",
    tags: ["audio", "thoughtful", "minimalist"],
    destinations: ["Kyoto", "Sound", "Nature"],
    alignmentScore: 0.83,
    weeklyVisitors: 142,
    followers: 3241,
    following: 188,
    online: true,
  },

  // ── Founders & Builders ────────────────────────────────────
  {
    id: "u-elena",
    name: "Elena Voss",
    handle: "@elena.build",
    avatarColor: "#FFD56B",
    avatarGlyph: "E",
    bio: "Building tech that doesn't make people anxious.",
    introVoiceSeconds: 16,
    city: "Amsterdam",
    tags: ["founder", "empath", "strategist"],
    destinations: ["Amsterdam", "StartupLife", "Mental-health"],
    alignmentScore: 0.87,
    weeklyVisitors: 512,
    followers: 18420,
    following: 744,
    online: true,
  },
  {
    id: "u-ravi",
    name: "Ravi Patel",
    handle: "@ravi.ship",
    avatarColor: "#34D399",
    avatarGlyph: "R",
    bio: "Shipping one quiet product at a time.",
    introVoiceSeconds: 10,
    city: "Mumbai",
    tags: ["founder", "dev", "patient"],
    destinations: ["Mumbai", "StartupLife", "Dev"],
    alignmentScore: 0.84,
    weeklyVisitors: 322,
    followers: 8421,
    following: 412,
    online: false,
  },

  // ── Writers & Poets ────────────────────────────────────────
  {
    id: "u-sage",
    name: "Sage Williams",
    handle: "@sage.ink",
    avatarColor: "#FB7185",
    avatarGlyph: "S",
    bio: "Writing what I can't say out loud.",
    introVoiceSeconds: 7,
    city: "New York",
    tags: ["writer", "introvert", "deep-listener"],
    destinations: ["New York", "Poetry", "Healing"],
    alignmentScore: 0.75,
    weeklyVisitors: 188,
    followers: 6842,
    following: 344,
    online: true,
  },
  {
    id: "u-omar",
    name: "Omar Farouk",
    handle: "@omar.verse",
    avatarColor: "#B57BFF",
    avatarGlyph: "O",
    bio: "Poetry is how I map the world.",
    introVoiceSeconds: 9,
    city: "Cairo",
    tags: ["writer", "wanderer", "warm"],
    destinations: ["Cairo", "Poetry", "Travel"],
    alignmentScore: 0.71,
    weeklyVisitors: 144,
    followers: 5218,
    following: 622,
    online: false,
  },

  // ── Filmmakers & Visual ────────────────────────────────────
  {
    id: "u-nina",
    name: "Nina Bergström",
    handle: "@nina.lens",
    avatarColor: "#F97316",
    avatarGlyph: "N",
    bio: "Documenting quiet moments in loud places.",
    introVoiceSeconds: 12,
    city: "Stockholm",
    tags: ["filmmaker", "patient", "thoughtful"],
    destinations: ["Stockholm", "Film", "Nature"],
    alignmentScore: 0.80,
    weeklyVisitors: 268,
    followers: 9124,
    following: 412,
    online: true,
  },
  {
    id: "u-joel",
    name: "Joel Mwangi",
    handle: "@joel.frame",
    avatarColor: "#5EEAD4",
    avatarGlyph: "J",
    bio: "Documentary filmmaker. Truth is the best story.",
    introVoiceSeconds: 14,
    city: "Nairobi",
    tags: ["filmmaker", "warm", "host"],
    destinations: ["Nairobi", "Film", "Travel"],
    alignmentScore: 0.77,
    weeklyVisitors: 196,
    followers: 7342,
    following: 521,
    online: true,
  },

  // ── Chefs & Food ───────────────────────────────────────────
  {
    id: "u-hana",
    name: "Hana Kim",
    handle: "@hana.kitchen",
    avatarColor: "#FFD56B",
    avatarGlyph: "H",
    bio: "Fermentation, patience, and the art of waiting.",
    introVoiceSeconds: 11,
    city: "Busan",
    tags: ["chef", "patient", "minimalist"],
    destinations: ["Busan", "Food", "Slow"],
    alignmentScore: 0.73,
    weeklyVisitors: 168,
    followers: 6421,
    following: 288,
    online: false,
  },

  // ── Travelers & Wanderers ──────────────────────────────────
  {
    id: "u-alex",
    name: "Alex Okonkwo",
    handle: "@alex.wander",
    avatarColor: "#A78BFA",
    avatarGlyph: "A",
    bio: "Digital nomad. 23 countries, no plan.",
    introVoiceSeconds: 8,
    city: "Accra",
    tags: ["wanderer", "creative", "curious"],
    destinations: ["Accra", "Travel", "Sound"],
    alignmentScore: 0.68,
    weeklyVisitors: 212,
    followers: 9842,
    following: 812,
    online: true,
  },

  // ── Wellness & Healing ─────────────────────────────────────
  {
    id: "u-maya",
    name: "Maya Santos",
    handle: "@maya.breathe",
    avatarColor: "#34D399",
    avatarGlyph: "M",
    bio: "Breathwork teacher. The pause is the practice.",
    introVoiceSeconds: 16,
    city: "Bali",
    tags: ["empath", "warm", "deep-listener"],
    destinations: ["Bali", "Healing", "Mental-health"],
    alignmentScore: 0.89,
    weeklyVisitors: 412,
    followers: 14204,
    following: 322,
    online: true,
  },
  {
    id: "u-thabo",
    name: "Thabo Ndlovu",
    handle: "@thabo.still",
    avatarColor: "#FB7185",
    avatarGlyph: "T",
    bio: "Mindfulness in the noise. Healing through sound.",
    introVoiceSeconds: 13,
    city: "Cape Town",
    tags: ["audio", "empath", "thoughtful"],
    destinations: ["Cape Town", "Healing", "Sound"],
    alignmentScore: 0.82,
    weeklyVisitors: 288,
    followers: 8421,
    following: 412,
    online: false,
  },

  // ── Researchers & Educators ────────────────────────────────
  {
    id: "u-clara",
    name: "Clara Hoffman",
    handle: "@clara.think",
    avatarColor: "#B57BFF",
    avatarGlyph: "C",
    bio: "Cognitive science. How we think about thinking.",
    introVoiceSeconds: 14,
    city: "Vienna",
    tags: ["strategist", "thoughtful", "deep-listener"],
    destinations: ["Vienna", "Healing", "Founders"],
    alignmentScore: 0.81,
    weeklyVisitors: 188,
    followers: 5218,
    following: 288,
    online: true,
  },

  // ── Gamers & Interactive ───────────────────────────────────
  {
    id: "u-ryu",
    name: "Ryu Hayashi",
    handle: "@ryu.play",
    avatarColor: "#F472B6",
    avatarGlyph: "R",
    bio: "Indie game design. Stories you can touch.",
    introVoiceSeconds: 10,
    city: "Osaka",
    tags: ["dev", "creative", "collector"],
    destinations: ["Osaka", "Game-dev", "Dev"],
    alignmentScore: 0.79,
    weeklyVisitors: 224,
    followers: 6421,
    following: 344,
    online: true,
  },

  // ── Additional diversity ───────────────────────────────────
  {
    id: "u-fatima",
    name: "Fatima Al-Rashid",
    handle: "@fatima.code",
    avatarColor: "#5EEAD4",
    avatarGlyph: "F",
    bio: "Arabic typography on the web. Letters have feelings.",
    introVoiceSeconds: 9,
    city: "Dubai",
    tags: ["dev", "creative", "color-obsessed"],
    destinations: ["Dubai", "Dev", "Design"],
    alignmentScore: 0.76,
    weeklyVisitors: 188,
    followers: 4218,
    following: 244,
    online: true,
  },
  {
    id: "u-jonas",
    name: "Jonas Ek",
    handle: "@jonas.light",
    avatarColor: "#FFD56B",
    avatarGlyph: "J",
    bio: "Lighting designer. The shadows are the story.",
    introVoiceSeconds: 12,
    city: "Helsinki",
    tags: ["filmmaker", "patient", "minimalist"],
    destinations: ["Helsinki", "Film", "Nature"],
    alignmentScore: 0.74,
    weeklyVisitors: 142,
    followers: 3241,
    following: 188,
    online: false,
  },
  {
    id: "u-chioma",
    name: "Chioma Eze",
    handle: "@chioma.art",
    avatarColor: "#F97316",
    avatarGlyph: "C",
    bio: "Afrofuturist art. The future is already here.",
    introVoiceSeconds: 11,
    city: "Lagos",
    tags: ["creative", "warm", "host"],
    destinations: ["Lagos", "Film", "Travel"],
    alignmentScore: 0.78,
    weeklyVisitors: 312,
    followers: 11204,
    following: 521,
    online: true,
  },
  {
    id: "u-oliver",
    name: "Oliver Strand",
    handle: "@oliver.quiet",
    avatarColor: "#A78BFA",
    avatarGlyph: "O",
    bio: "Quiet design. The user shouldn't notice the interface.",
    introVoiceSeconds: 8,
    city: "Copenhagen",
    tags: ["dev", "minimalist", "thoughtful"],
    destinations: ["Copenhagen", "Dev", "Design"],
    alignmentScore: 0.85,
    weeklyVisitors: 168,
    followers: 4821,
    following: 211,
    online: true,
  },
  {
    id: "u-ava",
    name: "Ava Torres",
    handle: "@ava.seed",
    avatarColor: "#34D399",
    avatarGlyph: "A",
    bio: "Seed-stage investor. Backing the quiet ones.",
    introVoiceSeconds: 15,
    city: "Austin",
    tags: ["founder", "strategist", "empath"],
    destinations: ["Austin", "StartupLife", "Founders"],
    alignmentScore: 0.83,
    weeklyVisitors: 412,
    followers: 14204,
    following: 642,
    online: false,
  },
  {
    id: "u-lucas",
    name: "Lucas Moreau",
    handle: "@lucas.wave",
    avatarColor: "#FB7185",
    avatarGlyph: "L",
    bio: "Surfing and synths. The ocean is the best producer.",
    introVoiceSeconds: 7,
    city: "Lisbon",
    tags: ["composer", "wanderer", "night-walker"],
    destinations: ["Lisbon", "Sound", "Travel"],
    alignmentScore: 0.72,
    weeklyVisitors: 188,
    followers: 5842,
    following: 412,
    online: true,
  },
  {
    id: "u-nadia",
    name: "Nadia Kowalski",
    handle: "@nadia.slow",
    avatarColor: "#B57BFF",
    avatarGlyph: "N",
    bio: "Slow living advocate. Unhurried is not unproductive.",
    introVoiceSeconds: 13,
    city: "Kraków",
    tags: ["writer", "patient", "thoughtful"],
    destinations: ["Kraków", "Slow", "Healing"],
    alignmentScore: 0.80,
    weeklyVisitors: 224,
    followers: 7421,
    following: 344,
    online: false,
  },
  {
    id: "u-tariq",
    name: "Tariq Hassan",
    handle: "@tariq.map",
    avatarColor: "#5EEAD4",
    avatarGlyph: "T",
    bio: "Urban planning through community voices.",
    introVoiceSeconds: 10,
    city: "Casablanca",
    tags: ["builder", "warm", "strategist"],
    destinations: ["Casablanca", "Travel", "Founders"],
    alignmentScore: 0.76,
    weeklyVisitors: 168,
    followers: 5218,
    following: 412,
    online: true,
  },
  {
    id: "u-sofia",
    name: "Sofia Lindqvist",
    handle: "@sofia.craft",
    avatarColor: "#FFD56B",
    avatarGlyph: "S",
    bio: "Handmade ceramics and digital pottery.",
    introVoiceSeconds: 9,
    city: "Gothenburg",
    tags: ["creative", "patient", "collector"],
    destinations: ["Gothenburg", "Slow", "Nature"],
    alignmentScore: 0.71,
    weeklyVisitors: 128,
    followers: 3842,
    following: 288,
    online: true,
  },
  {
    id: "u-james",
    name: "James Oduya",
    handle: "@james.build",
    avatarColor: "#F472B6",
    avatarGlyph: "J",
    bio: "Community builder. Tech should serve people.",
    introVoiceSeconds: 14,
    city: "Nairobi",
    tags: ["founder", "empath", "warm"],
    destinations: ["Nairobi", "StartupLife", "Mental-health"],
    alignmentScore: 0.84,
    weeklyVisitors: 341,
    followers: 10204,
    following: 521,
    online: true,
  },
  {
    id: "u-mila",
    name: "Mila Novak",
    handle: "@mila.echo",
    avatarColor: "#A78BFA",
    avatarGlyph: "M",
    bio: "Echoes of the Balkans. Sound as memory.",
    introVoiceSeconds: 12,
    city: "Zagreb",
    tags: ["audio", "deep-listener", "wanderer"],
    destinations: ["Zagreb", "Sound", "Travel"],
    alignmentScore: 0.73,
    weeklyVisitors: 142,
    followers: 3241,
    following: 244,
    online: false,
  },
  {
    id: "u-ethan",
    name: "Ethan Cole",
    handle: "@ethan.system",
    avatarColor: "#34D399",
    avatarGlyph: "E",
    bio: "Systems thinking for social good.",
    introVoiceSeconds: 11,
    city: "Melbourne",
    tags: ["strategist", "dev", "thoughtful"],
    destinations: ["Melbourne", "StartupLife", "Dev"],
    alignmentScore: 0.82,
    weeklyVisitors: 268,
    followers: 7421,
    following: 344,
    online: true,
  },
  {
    id: "u-aisha",
    name: "Aisha Bello",
    handle: "@aisha.threads",
    avatarColor: "#F97316",
    avatarGlyph: "A",
    bio: "Textile art meets code. Weaving digital futures.",
    introVoiceSeconds: 8,
    city: "Abuja",
    tags: ["creative", "dev", "warm"],
    destinations: ["Abuja", "Dev", "Design"],
    alignmentScore: 0.77,
    weeklyVisitors: 188,
    followers: 5218,
    following: 412,
    online: true,
  },
  {
    id: "u-viktor",
    name: "Viktor Petrov",
    handle: "@viktor.quiet",
    avatarColor: "#FB7185",
    avatarGlyph: "V",
    bio: "Quiet interfaces. The design you don't notice.",
    introVoiceSeconds: 10,
    city: "Tallinn",
    tags: ["dev", "minimalist", "introvert"],
    destinations: ["Tallinn", "Dev", "Design"],
    alignmentScore: 0.86,
    weeklyVisitors: 196,
    followers: 4218,
    following: 188,
    online: false,
  },
  {
    id: "u-rosa",
    name: "Rosa Martínez",
    handle: "@rosa.color",
    avatarColor: "#B57BFF",
    avatarGlyph: "R",
    bio: "Color theory for the soul. Every hue tells a story.",
    introVoiceSeconds: 9,
    city: "Buenos Aires",
    tags: ["creative", "color-obsessed", "warm"],
    destinations: ["Buenos Aires", "Film", "Travel"],
    alignmentScore: 0.75,
    weeklyVisitors: 212,
    followers: 6842,
    following: 521,
    online: true,
  },
  {
    id: "u-daniel",
    name: "Daniel Kim",
    handle: "@daniel.still",
    avatarColor: "#5EEAD4",
    avatarGlyph: "D",
    bio: "Meditation teacher. Stillness is not emptiness.",
    introVoiceSeconds: 16,
    city: "Vancouver",
    tags: ["empath", "deep-listener", "thoughtful"],
    destinations: ["Vancouver", "Healing", "Nature"],
    alignmentScore: 0.88,
    weeklyVisitors: 312,
    followers: 11204,
    following: 288,
    online: true,
  },
  {
    id: "u-layla",
    name: "Layla Osman",
    handle: "@layla.mosaic",
    avatarColor: "#FFD56B",
    avatarGlyph: "L",
    bio: "Mosaic art. Building beauty from broken pieces.",
    introVoiceSeconds: 7,
    city: "Istanbul",
    tags: ["creative", "patient", "warm"],
    destinations: ["Istanbul", "Travel", "Healing"],
    alignmentScore: 0.74,
    weeklyVisitors: 168,
    followers: 4821,
    following: 344,
    online: false,
  },
  {
    id: "u-oscar",
    name: "Oscar Lindgren",
    handle: "@oscar.type",
    avatarColor: "#A78BFA",
    avatarGlyph: "O",
    bio: "Typeface design. Every letter has a personality.",
    introVoiceSeconds: 11,
    city: "Malmö",
    tags: ["creative", "minimalist", "collector"],
    destinations: ["Malmö", "Design", "Dev"],
    alignmentScore: 0.81,
    weeklyVisitors: 148,
    followers: 4218,
    following: 211,
    online: true,
  },
];

/**
 * Additional seed posts for the expanded user network.
 * These posts give the new users content to surface in the feed.
 */
export const EXPANDED_POSTS: Post[] = [
  {
    id: "p-11",
    authorId: "u-zara",
    kind: "media",
    body: "New 3D render — what if social spaces looked like this? No likes, no numbers, just presence.",
    mediaTone: "nebula1",
    destinations: ["Dev", "Game-dev"],
    resonance: { spark: 412, flame: 88, echo: 34, sync: 21, resonate: 67, link: 19 },
    energy: 0.82,
    createdAt: now - 1000 * 60 * 25,
    commentCount: 38,
    shareCount: 14,
  },
  {
    id: "p-12",
    authorId: "u-sam",
    kind: "project",
    body: "Open-sourcing a tiny tool for building quieter interfaces. No tracking, no analytics, just the craft.",
    mediaTone: "none",
    destinations: ["Dev", "OSS"],
    project: { tasks: [{ label: "Write README", done: true }, { label: "Add examples", done: false }, { label: "Ship v1", done: false }] },
    resonance: { spark: 268, flame: 41, echo: 52, sync: 119, resonate: 12, link: 33 },
    energy: 0.76,
    createdAt: now - 1000 * 60 * 45,
    commentCount: 52,
    shareCount: 28,
  },
  {
    id: "p-13",
    authorId: "u-amara",
    kind: "voice",
    body: "Recorded this at dawn — the city waking up, one breath at a time.",
    mediaTone: "nebula2",
    voiceSeconds: 28,
    destinations: ["Sound", "Healing"],
    resonance: { spark: 511, flame: 28, echo: 19, sync: 67, resonate: 132, link: 22 },
    energy: 0.88,
    createdAt: now - 1000 * 60 * 60,
    commentCount: 88,
    shareCount: 33,
  },
  {
    id: "p-14",
    authorId: "u-elena",
    kind: "classic",
    body: "Stopped tracking metrics this week. The product got better. The team got happier. Coincidence? No.",
    mediaTone: "none",
    destinations: ["StartupLife", "Mental-health"],
    resonance: { spark: 822, flame: 191, echo: 44, sync: 38, resonate: 122, link: 17 },
    energy: 0.91,
    createdAt: now - 1000 * 60 * 60 * 2,
    commentCount: 124,
    shareCount: 48,
  },
  {
    id: "p-15",
    authorId: "u-sage",
    kind: "question",
    body: "What's one sentence you wish someone had said to you a year ago?",
    mediaTone: "none",
    destinations: ["Poetry", "Healing"],
    resonance: { spark: 1204, flame: 312, echo: 87, sync: 44, resonate: 188, link: 61 },
    energy: 0.94,
    createdAt: now - 1000 * 60 * 60 * 3,
    commentCount: 224,
    shareCount: 92,
  },
  {
    id: "p-16",
    authorId: "u-joel",
    kind: "media",
    body: "Dawn in Nairobi — the light tells a story that words can't. Three frames from today's shoot.",
    mediaTone: "nebula3",
    destinations: ["Film", "Nairobi"],
    resonance: { spark: 612, flame: 88, echo: 21, sync: 188, resonate: 54, link: 27 },
    energy: 0.84,
    createdAt: now - 1000 * 60 * 60 * 4,
    commentCount: 68,
    shareCount: 22,
  },
  {
    id: "p-17",
    authorId: "u-maya",
    kind: "voice",
    body: "A 60-second breathwork guide for when the world is too loud. Close your eyes and press play.",
    mediaTone: "nebula1",
    voiceSeconds: 42,
    destinations: ["Healing", "Mental-health"],
    resonance: { spark: 942, flame: 141, echo: 68, sync: 88, resonate: 224, link: 31 },
    energy: 0.96,
    createdAt: now - 1000 * 60 * 60 * 5,
    commentCount: 188,
    shareCount: 72,
  },
  {
    id: "p-18",
    authorId: "u-kai",
    kind: "classic",
    body: "Design is not what it looks like. Design is how it breathes. The best interfaces are the ones you forget.",
    mediaTone: "none",
    destinations: ["Dev", "Design"],
    resonance: { spark: 341, flame: 52, echo: 18, sync: 94, resonate: 41, link: 14 },
    energy: 0.72,
    createdAt: now - 1000 * 60 * 60 * 6,
    commentCount: 42,
    shareCount: 18,
  },
  {
    id: "p-19",
    authorId: "u-priya",
    kind: "project",
    body: "Building a tool for founders who hate meetings. Async-first, voice-optional, no FOMO.",
    mediaTone: "none",
    destinations: ["StartupLife", "Dev"],
    project: { tasks: [{ label: "User research", done: true }, { label: "MVP prototype", done: true }, { label: "Beta test with 10 founders", done: false }] },
    resonance: { spark: 418, flame: 88, echo: 34, sync: 142, resonate: 67, link: 28 },
    energy: 0.79,
    createdAt: now - 1000 * 60 * 60 * 7,
    commentCount: 72,
    shareCount: 28,
  },
  {
    id: "p-20",
    authorId: "u-felix",
    kind: "voice",
    body: "Midnight jazz session — the piano was cold, the room was empty, and the music was perfect.",
    mediaTone: "nebula2",
    voiceSeconds: 34,
    destinations: ["Sound", "Paris"],
    resonance: { spark: 388, flame: 62, echo: 28, sync: 44, resonate: 88, link: 14 },
    energy: 0.81,
    createdAt: now - 1000 * 60 * 60 * 8,
    commentCount: 56,
    shareCount: 22,
  },
  {
    id: "p-21",
    authorId: "u-james",
    kind: "question",
    body: "What would social media look like if it was designed for 80-year-olds instead of 18-year-olds?",
    mediaTone: "none",
    destinations: ["StartupLife", "Mental-health"],
    resonance: { spark: 722, flame: 141, echo: 88, sync: 67, resonate: 94, link: 41 },
    energy: 0.86,
    createdAt: now - 1000 * 60 * 60 * 9,
    commentCount: 148,
    shareCount: 62,
  },
  {
    id: "p-22",
    authorId: "u-nina",
    kind: "media",
    body: "Stockholm in December — 4 hours of light, 20 hours of beauty. Every shadow is a scene.",
    mediaTone: "nebula3",
    destinations: ["Film", "Stockholm"],
    resonance: { spark: 514, flame: 88, echo: 34, sync: 44, resonate: 67, link: 14 },
    energy: 0.83,
    createdAt: now - 1000 * 60 * 60 * 10,
    commentCount: 64,
    shareCount: 24,
  },
];

/**
 * Additional seed voice rooms for the expanded user network.
 */
export const EXPANDED_VOICE_ROOMS: VoiceRoom[] = [
  {
    id: "vr-6",
    topic: "3am design critiques — no holds barred",
    vibe: "Honest",
    hostId: "u-kai",
    speakers: ["u-kai", "u-oliver"],
    listeners: 67,
    live: true,
  },
  {
    id: "vr-7",
    topic: "Breathwork for builders",
    vibe: "Calm",
    hostId: "u-maya",
    speakers: ["u-maya", "u-thabo"],
    listeners: 224,
    live: true,
  },
  {
    id: "vr-8",
    topic: "What are you shipping this week?",
    vibe: "Warm",
    hostId: "u-priya",
    speakers: ["u-priya", "u-sam", "u-james"],
    listeners: 142,
    live: true,
  },
  {
    id: "vr-9",
    topic: "Late night jazz — bring your instrument",
    vibe: "Creative",
    hostId: "u-felix",
    speakers: ["u-felix", "u-amara"],
    listeners: 88,
    live: true,
  },
  {
    id: "vr-10",
    topic: "Quiet founders — what's keeping you up?",
    vibe: "Tender",
    hostId: "u-elena",
    speakers: ["u-elena", "u-ava"],
    listeners: 312,
    live: true,
  },
];


