// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/elysium-feed/AmbientLayers.tsx": () =>
    import("../components/mockups/elysium-feed/AmbientLayers.tsx"),
  "./components/mockups/elysium-feed/ConstellationFeed.tsx": () =>
    import("../components/mockups/elysium-feed/ConstellationFeed.tsx"),
  "./components/mockups/elysium-feed/FrequencyBoard.tsx": () =>
    import("../components/mockups/elysium-feed/FrequencyBoard.tsx"),
  "./components/mockups/elysium-feed/ResonancePulse.tsx": () =>
    import("../components/mockups/elysium-feed/ResonancePulse.tsx"),
};
