const palette = {
  void: "#07021A",
  deepSpace: "#0E0524",
  surface: "#170A2E",
  surfaceElev: "#221145",
  border: "#2C1656",
  text: "#F5F0FF",
  textMuted: "#A89AC8",
  textSubtle: "#6E5C99",
  primary: "#B57BFF",
  primaryDeep: "#7C3AED",
  gold: "#FFD56B",
  teal: "#5EEAD4",
  magenta: "#F472B6",
  rose: "#FB7185",
  emerald: "#34D399",
  destructive: "#F43F5E",
};

const colors = {
  light: {
    text: palette.text,
    tint: palette.primary,
    background: palette.void,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    cardElev: palette.surfaceElev,
    primary: palette.primary,
    primaryDeep: palette.primaryDeep,
    primaryForeground: "#FFFFFF",
    secondary: palette.surfaceElev,
    secondaryForeground: palette.text,
    muted: palette.surface,
    mutedForeground: palette.textMuted,
    subtle: palette.textSubtle,
    accent: palette.gold,
    accentForeground: palette.void,
    teal: palette.teal,
    magenta: palette.magenta,
    rose: palette.rose,
    emerald: palette.emerald,
    gold: palette.gold,
    destructive: palette.destructive,
    destructiveForeground: "#FFFFFF",
    border: palette.border,
    input: palette.border,
  },
  radius: 22,
};

export default colors;
